// File generated by FlutterFire CLI.
// ignore_for_file: constant_identifier_names, lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: "AIzaSyCkEXEMPLO-CHAVE-UNICA",
        appId: "1:142672787863:web:8e0b12abcd98765ef4321",
        messagingSenderId: "142672787863",
        projectId: "daniconsultorio-349bf",
        authDomain: "daniconsultorio-349bf.firebaseapp.com",
        storageBucket: "daniconsultorio-349bf.appspot.com",
        measurementId: "G-EXEMPLO1234",
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: "AIzaSyCkANDROID-CHAVE-1234",
          appId: "1:142672787863:android:0e8fabc123456789",
          messagingSenderId: "142672787863",
          projectId: "daniconsultorio-349bf",
          storageBucket: "daniconsultorio-349bf.appspot.com",
        );
      case TargetPlatform.iOS:
        return const FirebaseOptions(
          apiKey: "AIzaSyCkIOS-CHAVE-5678",
          appId: "1:142672787863:ios:7e8fbcde98765432",
          messagingSenderId: "142672787863",
          projectId: "daniconsultorio-349bf",
          storageBucket: "daniconsultorio-349bf.appspot.com",
          iosBundleId: "com.daniele.plataforma",
        );
      case TargetPlatform.macOS:
        return const FirebaseOptions(
          apiKey: "AIzaSyCkMAC-CHAVE-9012",
          appId: "1:142672787863:ios:7e8fbcde98765432",
          messagingSenderId: "142672787863",
          projectId: "daniconsultorio-349bf",
          storageBucket: "daniconsultorio-349bf.appspot.com",
          iosBundleId: "com.daniele.plataforma",
        );
      case TargetPlatform.windows:
        return const FirebaseOptions(
          apiKey: "AIzaSyCkWIN-CHAVE-3456",
          appId: "1:142672787863:windows:9e8fbcde12345678",
          messagingSenderId: "142672787863",
          projectId: "daniconsultorio-349bf",
          storageBucket: "daniconsultorio-349bf.appspot.com",
        );
      case TargetPlatform.linux:
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
