// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOj5zAJowIcPAoHC2IbJPFSovzb31iwFU',
    appId: '1:142672787863:web:5d30f67901537eba2a2cd2',
    messagingSenderId: '142672787863',
    projectId: 'daniconsultorio-349bf',
    authDomain: 'daniconsultorio-349bf.firebaseapp.com',
    storageBucket: 'daniconsultorio-349bf.firebasestorage.app',
    measurementId: 'G-0TSZGB5D4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm46iKEJq8pXu42oy8R1yy4W5w9L6wgXM',
    appId: '1:142672787863:android:b9ea3671a7c0497b2a2cd2',
    messagingSenderId: '142672787863',
    projectId: 'daniconsultorio-349bf',
    storageBucket: 'daniconsultorio-349bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsrepYyX30SQOIRr5GD7wdbHlsv3OlWy8',
    appId: '1:142672787863:ios:de49b0966ad032ed2a2cd2',
    messagingSenderId: '142672787863',
    projectId: 'daniconsultorio-349bf',
    storageBucket: 'daniconsultorio-349bf.firebasestorage.app',
    iosBundleId: 'com.example.plataformaDaniela',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsrepYyX30SQOIRr5GD7wdbHlsv3OlWy8',
    appId: '1:142672787863:ios:de49b0966ad032ed2a2cd2',
    messagingSenderId: '142672787863',
    projectId: 'daniconsultorio-349bf',
    storageBucket: 'daniconsultorio-349bf.firebasestorage.app',
    iosBundleId: 'com.example.plataformaDaniela',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOj5zAJowIcPAoHC2IbJPFSovzb31iwFU',
    appId: '1:142672787863:web:f5374a870a76842c2a2cd2',
    messagingSenderId: '142672787863',
    projectId: 'daniconsultorio-349bf',
    authDomain: 'daniconsultorio-349bf.firebaseapp.com',
    storageBucket: 'daniconsultorio-349bf.firebasestorage.app',
    measurementId: 'G-RLY8Q09YK7',
  );
}
